name: build and test Backend

on: [push]
jobs:
  doc:
    runs-on: ubuntu-latest

    permissions:
      # Required to push changes!
      contents: write

    steps:
    - uses: actions/checkout@v4

    -  run: |
        echo "<!--doc_begin-->\n<!--doc_end-->" > README.md
    - uses: pndurette/gh-actions-auto-docs@v1
      with:
        action_yaml_file: ./action.yml
        target_file: abc.md
    - run: |
        cat abc.md
        
