name: build and test Backend

on: [push]

jobs:
  
  compliance:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4


    - name: Install dependencies

      run: |
        echo "hallo welt"
