name: build and test Backend

on: [push]

jobs:
  
  compliance:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

  produce-artifacts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        color: ["red", "green", "blue"]
    steps:
      - id: str1
        env:
          color: ${{ matrix.color }}
        run: |
          echo "$color" 
          # echo "color=${color}" >> "$GITHUB_OUTPUT"
      - name: a
        run: |
          echo $color
          echo ${{ steps.str1.outputs.color }}
