# Workflow for running security scan using Trivy
name: trivy

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron:  '*/5 * * * *'
    # cron: '30 5 * * 1'
      timezone: "Europe/Berlin"

jobs:
  trivy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write # Required to upload SARIF results to the GitHub Security tab
    steps:
      - run: |
         echo "hallo"
